#!/bin/bash

# Check if Gunicorn is running
if pgrep -x "gunicorn" > /dev/null
then
    # Send HUP signal to reload Gunicorn gracefully
    sudo kill -HUP $(pgrep gunicorn)
    echo "Gunicorn reloaded gracefully."
else
    echo "Gunicorn is not running."
fi
